### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by AdamYLiang** [ppondo/Uncorkd#2]
- [x] Checkins should be nested underneath the user that created them. (`/user/:user_id/checkin/:checkin_id`)
- [x] Only need a `/beverage/:beverage_id` since you can use modal/ui_state to determine when forms should appear.

**Comment by ppondo** [comment]
Got it, I am not sure how to reference the use of a modal so please let me know if there is anything else to change.

**Comment by AdamYLiang** [comment]
Looks good! We'll go over modal usage once you get to that MVP!
