### ISSUE TITLE
Breweries MVP 

### ISSUE THREAD

**Issue by AdamYLiang** [ppondo/Uncorkd#4]
- [x] Logging out the user on the `/home` route seems to not redirect user to splash page. 
- [x] Have nav bar with user icon and dropdown

**CSS**
- [x] Top nav bar text should be centered a bit more. 

When everything is done I would recommend seeding more data to make it look even more impressive!

**Comment by ppondo** [comment]
got it!

**Comment by AdamYLiang** [comment]
Nice changes, just one more thing: 
- [ ] If you click on `My Profile` from the nav dropdown, it routes you to a wildcard ID. If you then attempt to log out it will not reroute you.
